### ISSUE TITLE
REST API 

### ISSUE THREAD

**Issue by cshinaver** [ccastil1/SoftwareEngineering#5]
This is the master issue which will be broken up into sub issues
- [x] Setup initial "files" service with our file model
- [x] GET /files/download/:filename Initiates download of file with given filename. #7 
- [x] GET /files/:filename  Returns metadata associated with given filename. #8 
- [x] POST /files : args: /file- data to upload /filename- name to be assigned in filesystem Initiates upload of given file.
- [x] GET /files : Returns listing of all filenames available to the user session. #10 
- [x] DELETE /files/:filename : Remove given file from system. #12

**Comment by cmcmil** [comment]
Hi All.  I was able to get the latest version up and running, and to read through your code for these API functions.  Looks like you have it working as far as the database is concerned, but still have to add functionality to actually store the files.  You probably have a plan for this.  If not, I suggest just adding one file manually and making the DELETE and GET /files/download/:filename to work.  That way you don't have to make POST /files first.

**Comment by cmcmil** [comment]
Where is the API input/output documented?  A GET /files/test123 gives me (for example):

{'name': 'test123', 'attachment_file_size': 14, 'created_at': '2016-11-14T19:50:31.150Z', 'updated_at': '2016-11-14T19:50:31.150Z', 'attachment_updated_at': '2016-11-14T19:50:31.128Z', 'attachment_content_type': 'text/plain', 'id': 3, 'attachment_file_name': 'test.txt'}

I had to just go get this.  It wasn't hard, but I wonder if you have a central place where you're keeping the interface docs.

Side question: how do you determine the content_type?

**Comment by spmike** [comment]
The interface docs will be added to the readme. For determining content_type, we use paperclip which automatically determines it for us.
